apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jxow2jgaq-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jxow2jgaq-go 
  name: jxow2jgaq-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jxow2jgaq-go 
